openapi: '3.0.2'
info:
  title: Botpress API App
  version: '1.0'
servers:
  - url: http://localhost:9090
paths:
  /get/user:
    post:
      responses:
        '200':
          description: OK
        '500':
          description: ERROR
  /get/canteen_menu:
    post:
      responses:
        '200':
          description: OK
        '500':
          description: ERROR
  /get/temperature:
    post:
      responses:
        '200':
          description: OK
        '500':
          description: ERROR
  /get/humidity:
    post:
      responses:
        '200':
          description: OK
        '500':
          description: ERROR
  /set/sendmail:
    post:
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                recipient:
                  type: string
                subject:
                  type: string
                bodytext:
                  type: string
      responses:
        '200':
          description: OK
        '500':
          description: ERROR